### ISSUE TITLE
Settings exposure

### ISSUE THREAD

**Issue by xavxyz** [bySabi/neal-sample-meteor#1]
Hi ! Looking around how you have built this landing page app, I found your settings exposed in the code : https://github.com/bySabi/neal-sample-meteor/blob/master/src/App/client/ui/App.jsx#L10
You may want to pass it through a `settings.json` file to make the app more configurable and not exposing your own data in (stripe key :8ball: ) ?
Cheers

**Comment by bySabi** [comment]
Thanks for pointing out.
At present time this project is a meteor port of this: https://github.com/dennybritz/neal-sample/blob/master/js/app.jsx#L10 just a copy/paste.

Feel free to PR improvements :-)

**Comment by xavxyz** [comment]
Haha ok! No probs :+1:
